### ISSUE TITLE
ERROR: dependencies 'Gviz', 'biomaRt' are not available for package 'eQTpLot'

### ISSUE THREAD

**Issue by jielab** [RitchieLab/eQTpLot#10]
Hi, there:

I trired to install, but got the following errors. It seems that a lot of dependency packages are not available for R 4.1.1.

ERROR: dependencies 'Gviz', 'biomaRt' are not available for package 'eQTpLot'
* removing 'D:/software_win/R_lib/eQTpLot'
Warning messages:
1: packages ‘snpStats’, ‘biomaRt’, ‘Gviz’ are not available for this version of R
Versions of these packages for your version of R might be available elsewhere,

Can you please kindly provide an easy solution so that I could get this installed?

Thank you very much & best regards,
Jie

**Comment by anastasia-lucas** [comment]
Hi Jie, 

Thanks for using our package.

Can you try installing those packages first using `BiocManager`?

`if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")`
`BiocManager::install("Gviz")`
`BiocManager::install("biomaRt")`
`BiocManager::install("snpStats")`

Then try installing `eQTpLot` again using `devtools::install_github("RitchieLab/eQTpLot")`

**Comment by jielab** [comment]
Dear Anastasia:

Thanks!

Please see the screenshot below. Now there is a new message. It still does not work. 
![image](https://user-images.githubusercontent.com/26947455/132864046-71fef46b-8b32-4f61-92f8-a9af261628d0.png)

Best regards,
Jie

**Comment by anastasia-lucas** [comment]
Hi Jie,

Are you able to install other packages from GitHub using `devtools::install()`? 

If you need a lightweight test with no dependencies, you could try `devtools::install_github("anastasia-lucas/sqlizeR")` or any other R package.

Unfortunately `install.packages()` method won't work as this is not on CRAN.

**Comment by jielab** [comment]
Dear Anastasia:

I tried it again and this time it worked. Please see attached.

![image](https://user-images.githubusercontent.com/26947455/132897267-8704757f-a063-486b-885a-2ac1c22acff0.png)

There days there are many many tools about colocalization analysis. So, eQTpLot is mainly for "plot" after the colocalization analysis was done? Is there a pipelien for conducting colocalization analysis at genome-wide level?

Don't know if you are aware of LocusFocus, which claims to do the colocalization analysis through an easy web interface. I tried it too, but it did not work yet.

Best regards,
Jie

**Comment by anastasia-lucas** [comment]
Hi Jie, 

Yes, you are correct that eQTpLot is focused on the visualization.

I am not aware of any existing pipeline, but I know that a few people in my group are working on making a pipeline available for conducting colocalization between GWAS trait and eQTL.
