### ISSUE TITLE
Labeling problem

### ISSUE THREAD

**Issue by KomiGH** [RitchieLab/eQTpLot#15]
Hi, I am using your plotting package and I ran into the same problem like SaeidehTD. The labeling of eQTL and Non-eQTL in the C. plot is different like in here in the github example. When I run the same code in my own computer I got a differently labelled plot (see attached image). I saw that the problem was solved for SaeidehTD , but I don't see the solution. I uninstalled and reinstalled the package but I have the same issue. Can you help me with that? Thank You, Peter

![image](https://user-images.githubusercontent.com/105348259/167800381-65bdd949-aee5-4e08-89a3-314160edcb38.png)

**Comment by TGDrivas** [comment]
Hi Peter, sorry it looks like I made an error when fixing this problem for SaeidehTD. Could you try installing the latest commit of eQTpLot (I just updated it) and let me know if that resolves the issue. Thank you!

**Comment by KomiGH** [comment]
Hi, thank you it is working now perfectly!

**Comment by TGDrivas** [comment]
Great!
