### ISSUE TITLE
issue with biomaRt connection and hg38 build

### ISSUE THREAD

**Issue by aschluter** [RitchieLab/eQTpLot#16]
Hi,

thanks for this fantastic package! It is very useful.

I got a problem when trying eQTpLot function with hg38 build.

eQTpLot(GWAS.df = GWAS.df, eQTL.df = eQTL.df, gene = "LPAR1", gbuild = "hg38",  
        trait = "cerebral", tissue =  "Whole_Blood", CollapseMethod = "min") 

Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose) : Internal Server Error (HTTP 500).

I changed the BioMart hostname to www.ensembl.org (instead of https://apr2020.archive.ensembl.org). Then the connection works sometimes, or sometimes another error appears.

Error in bmRequest(request = request, httr_config = httr_config, verbose = verbose):
  Gateway timeout (HTTP 504)

Is it possible to avoid the connection to biomaRt and work with a downloadable database file?

Thank you,
Best,

Agatha

**Comment by TGDrivas** [comment]
Hello Agatha,

Thank you for the suggestion! We are working on a new release of the eQTpLot package and will absolutely take this suggestion into account. Thank you for providing this modification to the code that seems to help a bit in the mean time. 

Teddy
