### ISSUE TITLE
installing 

### ISSUE THREAD

**Issue by MoMaz123** [RitchieLab/eQTpLot#17]
Hi, I am trying to download it but keep getting this error. your help is appreciated! 

Installing package into ‘C:/Users/xxxx/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
ERROR: dependencies 'Gviz', 'GenomicRanges', 'biomaRt', 'LDheatmap' are not available for package 'eQTpLot'
* removing 'C:/Users/xxxx/AppData/Local/R/win-library/4.2/eQTpLot'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/xxxx//AppData/Local/Temp/RtmpCGKAcV/file301c6a791a9e/eQTpLot_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by TGDrivas** [comment]
Hello,

Could you please try installing the packages 'Gviz', 'GenomicRanges', 'biomaRt', and 'LDheatmap' before installing eQTpLot and see if that makes a difference?

**Comment by MoMaz123** [comment]
thanks, its solved now.best, mohsen
    On Monday, 2 October 2023 at 16:26:31 BST, TGDrivas ***@***.***> wrote:  
 
 


Hello,

Could you please try installing the packages 'Gviz', 'GenomicRanges', 'biomaRt', and 'LDheatmap' before installing eQTpLot and see if that makes a difference?
