### ISSUE TITLE
BETA for NES?

### ISSUE THREAD

**Issue by yqhu96** [RitchieLab/eQTpLot#18]
In the eQTL data, is it feasible to replace NES with a simple BETA value? This is because it seems that only BETA values can be obtained from the data in eQTLGen (https://www.eqtlgen.org/cis-eqtls.html). Thank you!

**Comment by TGDrivas** [comment]
Yes, there should be no problem with using beta values instead of NES -- you will just need to keep the column header as "NES" for the script to work. The resulting plots will use your beta values to indicate the direction and size of effect.
