### ISSUE TITLE
congruence or not?

### ISSUE THREAD

**Issue by yqhu96** [RitchieLab/eQTpLot#20]
Considering that the positive or negative direction of the beta values for SNPs in GWAS can be achieved by swapping the effect allele and other allele, while in eQTL, there seems to be only one beta value, does this congruence still make sense?

**Comment by TGDrivas** [comment]
Thank you for pointing this out. Yes this is true -- this R package does not check to make sure that, for a given SNP, the effect allele is the same between the eQTL and GWAS data. We recommend that you ensure that your data are harmonized with regard to SNP identifier and effect allele before running eQTpLot. We will consider adding a harmonization step to future releases.
