### ISSUE TITLE
eQTpLot cannot be installed due to LDheatmap dependency

### ISSUE THREAD

**Issue by Zixuan-YU** [RitchieLab/eQTpLot#22]
Dear development team, 

`eQTpLot` cannot be installed due to the `LDheatmap` dependency. I saw that 'package `LDheatmap` has been removed from the CRAN repository'. [https://cran.r-project.org/web/packages/LDheatmap/index.html]
I tried to install previously available versions that can be obtained from the archive, but the installation process has errors so I cannot continue. My version of R is 4.3.0. Would you suggest another way to install the eQTpLot package?

Regards,
Zixuan

**Comment by TGDrivas** [comment]
Hello,

You should be able to install packages built for older versions of R using a command like:

install_github("SFUStatgen/LDheatmap")

Please let me know if this works.

**Comment by Zixuan-YU** [comment]
Dear development team,
This is working! Thanks for the clarification.
