### ISSUE TITLE
No plot generated

### ISSUE THREAD

**Issue by nickhir** [RitchieLab/eQTpLot#4]
Hi,

your package seems very interesting to me and I am currently trying it out. Thanks for sharing it!
However, I am currently struggling to actually display the plots I have generated (using version 0.0.0.9000). 
I followed all instruction and completed the installation without any errors. When I try to run this example:

```R
eQTpLot(GWAS.df = GWAS.df.example, eQTL.df = eQTL.df.example, gene = c("BBS1", "ACTN3"), 
        gbuild = "hg19",  trait = "LDL", tissue =  "all", CollapseMethod = "min", 
        GeneList = T)
```
I get the same output as in the tutorial: 
```R
[1] "Checking input data..."
[1] "PHE column found in GWAS.df. Analyzing data for phenotype LDL"
[1] "PanTissue eQTL analysis, collapsing by method  min  will be completed across all tissues in eQTL.df"
[1] "For genes:"
[1] "'BBS1', 'ACTN3'"
[1] "eQTL analysis for gene BBS1: Pearson correlation: 0.823, p-value: 1.62e-127" "eQTL analysis for gene ACTN3: Pearson correlation: 0.245, p-value: 1.52e-07"
[1] "Complete"
```
Despite the message saying everything worked fine, I can't seem to find the plot that was generated. It doesn't show up in the "Plots" tab of RStudio (`getplot=TRUE`), and also no plot is being generated in my working directory ( `saveplot=TRUE`).

Am I missing something very obvious?
Cheers!

**Comment by anastasia-lucas** [comment]
Hi, could you try to run the example in a new R session and then paste the output of `sessionInfo()` so I could try to reproduce the error?

**Comment by nickhir** [comment]
I think I figured out the "problem". I supplied two genes to the `gene` flag, so no plot was generated.
If I use:
```R
eQTpLot(GWAS.df = GWAS.df.example, eQTL.df = eQTL.df.example, gene = "BBS1", 
        gbuild = "hg19",  trait = "LDL", tissue =  "all", CollapseMethod = "min")
```

Everything works as intended and a plot is generated.

**Comment by anastasia-lucas** [comment]
Glad it is working! Thanks for raising this issue. 

I think it will be more user friendly for the package to produce an error this case and will work on an update for that.
